# Generated by Django 5.2 on 2025-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.TextField(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
